### ISSUE TITLE
Search Bar Font Size Too Small

### ISSUE THREAD

**Issue by loannaflip** [not-holar/my_firefox_theme#8]
I'm on 1920x1080 Resolution Monitor and the font size of the search bar and its text is too small. How to Increase it?
<img src="https://i.imgur.com/Ks5jJJv.png">

**Comment by loannaflip** [comment]
Thanks I Found it.
```css
#nav-bar {
	padding: 2px !important;
	font-size: 20px !important;
}
```
